version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3052:3052"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:3053

  backend:
    build: ./backend
    ports:
      - "3053:3053"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=product_management
      - DB_USER=admin
      - DB_PASSWORD=${DB_PASSWORD}

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: product_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: